### ISSUE TITLE
Add matrix transpose operation for GPU and CPU

### ISSUE THREAD

**Issue by uditarora** [karanchahal/buildTensorflow#6]
Build out transpose operation so that we can perform backProp of dot product

**Comment by karanchahal** [comment]
Update on this issue.
I've added the transpose operation on the CPu, it's a simple change to just changing the shape vector of the ND Matrix and no data rearranging required as the underlying data structure of a ND array is just a 1d vector. Will push this feature with the GPU Dot Product feature

**Comment by karanchahal** [comment]
So the transpose operations is handled via #21 . It is a simple change of the shape vector in our ND Array Matrix class. CLosing this issue for now as it is no longer reliant on GPU support.
